-- =========================================================
-- TABELA DE USUÁRIOS DO TelaLogin
-- Rode no Supabase: SQL Editor > New query > cole tudo > Run
-- =========================================================

-- Se você JÁ tinha criado a tabela com o nome "user", rode antes só estas
-- duas linhas (sem o "--") em vez do create table abaixo:
--   alter table public."user" rename to users;
--   alter table public.users add column role text not null default 'USER' check (role in ('USER', 'ADMIN'));

create table if not exists public.users (
    id            bigint      generated by default as identity primary key,
    email         text        not null unique,
    password_hash text        not null,
    name          text        not null,
    role          text        not null default 'USER' check (role in ('USER', 'ADMIN')),
    -- Dados do cadastro (/register). Aceitam NULL porque o admin não tem.
    cpf           text,
    rg            text,
    address       text,
    institution   text,
    created_at    timestamptz not null default now()
);

-- O Supabase expõe o schema "public" numa API REST pública (usa a "anon key",
-- que fica visível em qualquer front-end). Sem RLS, qualquer pessoa com essa
-- chave conseguiria ler a tabela, inclusive os hashes de senha.
-- Ligando o RLS SEM criar nenhuma policy, a API REST fica bloqueada.
-- O Spring Boot continua funcionando porque conecta como "postgres", o dono
-- da tabela, que não é afetado pelo RLS.
alter table public.users enable row level security;
